#配置config server的端口
server:
  port: 8081


spring:
  application:
    name: config-server #config server的serverId
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangfancying/spirng-config
          search-paths: /**
          username: wangfancying@163.com
          password: wanghui425508180
        #spring.cloud.config.server.encrypt.enabled设置是否禁用服务器端属性解密
        encrypt:
          enabled: false

# uri表示配置中心所在仓库的位置
# search-paths表示仓库下的子目录
# username表示你的GitHub用户名
# password表示你的GitHub密码
