spring:
  application:
    name: consumer-server
  rabbitmq:
    addresses: 192.168.33.10:5672
    username: guest
    password: guest
  sleuth:
      sampler:
        percentage: 1
  zipkin:
    base-url: http://localhost:8999

server:
  port: 8111
